#! /usr/bin/env bash

# user input arguments: directory with projects, password, port mapping, host machine renv cache (= container renv cache mount point)





docker run --name rstudio --restart=always -v ~/github/projects/:/home/rstudio/projects/ -e PASSWORD=yourpassword123 -dp 8899:8787 rocker/ml



# the location of the renv cache on the host machine
RENV_PATHS_CACHE_HOST=/opt/local/renv/cache

# where the cache should be mounted in the container
RENV_PATHS_CACHE_CONTAINER=/renv/cache

docker run --rm \
    -e "RENV_PATHS_CACHE=${RENV_PATHS_CACHE_CONTAINER}" \
    -v "${RENV_PATHS_CACHE_HOST}:${RENV_PATHS_CACHE_CONTAINER}" \
    -p 14618:14618 \
    R -s -e 'renv::restore(); shiny::runApp(host = "0.0.0.0", port = 14618)'
